/**
 * AI Art Video Command
 * Usage: .aiartvideo <prompt>
 */

const axios = require('axios');

// Replicate API Configuration
const REPLICATE_API_TOKEN = 'r8_Ua9NNqwunA2oSxOrY72d3Dfa8MS1vHe4Izs74';

module.exports = {
    name: 'aiartvideo',
    aliases: ['artvideo', 'videogen'],
    description: 'Generate an AI art video from text',
    category: 'media',
    async execute({ sock, msg, from, reply, args }) {
        const prompt = args.join(' ');
        if (!prompt) {
            return reply('🎬 Please provide a prompt for the AI video.\nExample: .aiartvideo Image of a cat dancing');
        }

        try {
            // Let the user know we're working on it
            await sock.sendMessage(from, { react: { text: '⏳', key: msg.key } });
            
            let videoUrl = null;

            // Attempt 1: Replicate API (High quality)
            try {
                const replicateRes = await axios.post(
                    'https://api.replicate.com/v1/predictions',
                    {
                        version: "db21e45d3f70234220732854b83f566d23b10e66a162883a158b9404c7002020", // Luma Dream Machine or similar
                        input: { prompt: prompt }
                    },
                    {
                        headers: {
                            'Authorization': `Token ${REPLICATE_API_TOKEN}`,
                            'Content-Type': 'application/json'
                        }
                    }
                );
                
                let prediction = replicateRes.data;
                // Poll for completion (simplified for bot environment)
                while (prediction.status !== 'succeeded' && prediction.status !== 'failed') {
                    await new Promise(resolve => setTimeout(resolve, 5000));
                    const pollRes = await axios.get(
                        `https://api.replicate.com/v1/predictions/${prediction.id}`,
                        {
                            headers: { 'Authorization': `Token ${REPLICATE_API_TOKEN}` }
                        }
                    );
                    prediction = pollRes.data;
                }
                
                if (prediction.status === 'succeeded') {
                    videoUrl = prediction.output;
                }
            } catch (replicateErr) {
                console.error('[aiartvideo] Replicate failed:', replicateErr.message);
            }

            // Attempt 2: Public API Fallback (Shikari or similar)
            if (!videoUrl) {
                try {
                    const res = await axios.get(`https://api.maher-zubair.tech/ai/text2video?q=${encodeURIComponent(prompt)}`);
                    videoUrl = res.data.result || res.data.url;
                } catch (fallbackErr) {
                    console.error('[aiartvideo] Fallback 1 failed:', fallbackErr.message);
                }
            }

            // Attempt 3: Another Public API Fallback
            if (!videoUrl) {
                try {
                    const res = await axios.get(`https://api.shikari.my.id/api/ai/text2video?prompt=${encodeURIComponent(prompt)}`);
                    videoUrl = res.data.result || res.data.url;
                } catch (fallbackErr2) {
                    console.error('[aiartvideo] Fallback 2 failed:', fallbackErr2.message);
                }
            }

            if (!videoUrl) {
                await sock.sendMessage(from, { react: { text: '❌', key: msg.key } });
                return reply('❌ Failed to generate video. All AI video servers are currently busy.');
            }

            await sock.sendMessage(from, {
                video: { url: videoUrl },
                mimetype: 'video/mp4',
                caption: `🎬 *AI Art Video*\n\n📝 *Prompt:* ${prompt}\n\n> Generated by SUKUNA MD`,
            }, { quoted: msg });

            await sock.sendMessage(from, { react: { text: '✅', key: msg.key } });
        } catch (err) {
            console.error('[aiartvideo]', err.message);
            await sock.sendMessage(from, { react: { text: '❌', key: msg.key } });
            reply('❌ AI Video generation failed. Please try again later.');
        }
    }
};
